FROM rust:1.49

RUN USER=root cargo new --bin holodeck
WORKDIR /holodeck

COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

RUN cargo build --release
RUN rm src/*.rs

COPY ./src ./src

RUN rm ./target/release/deps/holodeck*
RUN cargo install --path .

CMD ["holodeck"]